import cv2
import numpy as np
from typing import Tuple, Dict, Any, List
import logging

logger = logging.getLogger("steel_defect.weak_segmenter")

class WeakROIThresholdSegmenter:
    """
    Derived Weak Segmentation Engine.
    Generates binary defect masks from bounding box ROIs using adaptive thresholding,
    Otsu binarization, and morphological contour refinement.
    
    SCIENTIFIC NOTICE:
    Masks generated by this engine are derived weak masks inferred from 2D intensity contrast.
    They must NOT be reported as manually annotated pixel-level ground truth.
    """
    
    def __init__(self, blur_kernel: Tuple[int, int] = (5, 5), morphology_kernel_size: int = 3):
        self.blur_kernel = blur_kernel
        self.morph_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (morphology_kernel_size, morphology_kernel_size))

    def segment_roi(self, image: np.ndarray, bbox: Tuple[float, float, float, float]) -> np.ndarray:
        img_h, img_w = image.shape[:2]
        xmin, ymin, xmax, ymax = bbox

        # Clamp ROI bounds
        x1 = max(0, int(round(xmin)))
        y1 = max(0, int(round(ymin)))
        x2 = min(img_w, int(round(xmax)))
        y2 = min(img_h, int(round(ymax)))

        mask = np.zeros((img_h, img_w), dtype=np.uint8)

        if (x2 - x1) <= 1 or (y2 - y1) <= 1:
            return mask

        roi = image[y1:y2, x1:x2]
        if len(roi.shape) == 3:
            roi_gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
        else:
            roi_gray = roi.copy()

        # Gaussian Blur to smooth noise
        blurred = cv2.GaussianBlur(roi_gray, self.blur_kernel, 0)

        # Otsu thresholding within ROI
        bg_mean = np.mean(image)
        roi_mean = np.mean(roi_gray)

        # Invert if defect is darker than background
        if roi_mean < bg_mean:
            inv_blurred = 255 - blurred
            _, binary_roi = cv2.threshold(inv_blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        else:
            _, binary_roi = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

        # Morphological Closing & Opening
        binary_roi = cv2.morphologyEx(binary_roi, cv2.MORPH_CLOSE, self.morph_kernel)
        binary_roi = cv2.morphologyEx(binary_roi, cv2.MORPH_OPEN, self.morph_kernel)

        mask[y1:y2, x1:x2] = (binary_roi > 0).astype(np.uint8)

        return mask
